config/routes.rb
Rails.application.routes.draw do

  resources :deliverers do
    member do
      post 'refresh_map_view'
    end
  end
  devise_for :users
  root 'check_ins#index'

  resources :check_ins do
    collection do
      get 'import_csv'
      post 'process_csv'
      get 'delete_all'
      post 'confirm_delete_all'
      get 'show_on_map'
      post 'refresh_map_view'
    end
  end
  resources :sections do
    collection do
      get 'import_csv'
      post 'process_csv'
      get 'delete_all'
      post 'confirm_delete_all'
    end
    member do
      get 'show_per_time_slot'
      post 'refresh_per_time_slot'
      get 'show_per_day_of_week'
      post 'refresh_per_day_of_week'
      get 'show_avg_per_time_slot'
      post 'refresh_avg_per_time_slot'
      get 'show_avg_per_day_of_week'
      post 'refresh_avg_per_day_of_week'
      get 'show_check_ins_time_series'
      post 'refresh_check_ins_time_series'
      get 'download_csv_reports'
    end
  end
  resources :section_configurations do
    collection do
      get 'import_csv'
      post 'process_csv'
      get 'delete_all'
      post 'confirm_delete_all'
    end
  end

end

app/models/check_in.rb
class CheckIn < ActiveRecord::Base
	belongs_to :section
	belongs_to :deliverer
end

app/controllers/check_ins_controller.rb
require 'csv'

class CheckInsController < ApplicationController
  before_action :set_check_in, only: [:show, :edit, :update, :destroy]

  # GET /check_ins
  # GET /check_ins.json
  def index
    @check_ins = CheckIn.all.paginate(:page => params[:page], :per_page => 100)
  end

  # GET /check_ins/1
  # GET /check_ins/1.json
  def show
  end

  # GET /check_ins/new
  def new
    @check_in = CheckIn.new
  end

  # GET /check_ins/1/edit
  def edit
  end

  # POST /check_ins
  # POST /check_ins.json
  def create
    @check_in = CheckIn.new(check_in_params)

    respond_to do |format|
      if @check_in.save
        format.html { redirect_to @check_in, notice: 'Check in was successfully created.' }
        format.json { render :show, status: :created, location: @check_in }
      else
        format.html { render :new }
        format.json { render json: @check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /check_ins/1
  # PATCH/PUT /check_ins/1.json
  def update
    respond_to do |format|
      if @check_in.update(check_in_params)
        format.html { redirect_to @check_in, notice: 'Check in was successfully updated.' }
        format.json { render :show, status: :ok, location: @check_in }
      else
        format.html { render :edit }
        format.json { render json: @check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /check_ins/1
  # DELETE /check_ins/1.json
  def destroy
    @check_in.destroy
    respond_to do |format|
      format.html { redirect_to check_ins_url, notice: 'Check in was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

    def import_csv
  end

  def process_csv
    list_of_duplicates = []

    uploaded_file = params[:checkins_csv]
    check_in_batch,batch_size = [], 1_000 
    CSV.foreach(uploaded_file.path, {:headers => true, :col_sep => ",", :encoding => "iso-8859-1:utf-8"}) do |row|

      new_check_in = CheckIn.new(:latitude => row["START_LATITUD"].to_f,
                                 :longitude => row["START_LONGITUD"].to_f,
                                 :timestamp => DateTime.strptime(row["FHSTARTREAL"], '%Y-%m-%d %H:%M:%S'),
                                 :section_id => row["ID_TRAMO"].to_i)

      #

      #new_deliverer = Deliverer.where(:plate_number => row["COD_MATR"].to_s).first
      #if new_deliverer.nil?
      #  new_deliverer = Deliverer.new(:plate_number => row["COD_MATR"].to_s, :fleet_id => row["ID_USUARIO"].to_i)
      #  new_deliverer.save!
      #else
      #  if new_deliverer.fleet_id != row["ID_USUARIO"].to_i
      #    list_of_duplicates << new_deliverer.plate_number
      #  end
      #end

      #new_check_in.deliverer = new_deliverer
      
      check_in_batch << new_check_in

      if check_in_batch.size >= batch_size
        CheckIn.import check_in_batch
        check_in_batch = []
      end

    end
    CheckIn.import check_in_batch

    redirect_to :action => :index
  end

  def delete_all
  end

  def confirm_delete_all
    CheckIn.delete_all
    redirect_to :action => :index
  end

  def show_on_map
  end

  def refresh_map_view
    start_date = Date.strptime(params[:start_date], '%Y-%m-%d')
    end_date = Date.strptime(params[:end_date], '%Y-%m-%d')

    if params[:deliverer_id].blank?
      @check_ins = CheckIn.where("timestamp > ? and timestamp < ?", start_date, end_date)
    else
      deliverer_id = params[:deliverer_id].to_i
      @check_ins = []
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check_in
      @check_in = CheckIn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def check_in_params
      params.fetch(:check_in, {})
    end
end

app/helpers/check_ins_helper.rb
module CheckInsHelper
end

app/views/check_ins/_form.html.erb
<%= form_for @check_in, :html => { :class => "form-horizontal check_in" } do |f| %>

    <% if @check_in.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@check_in.errors.count, "error") %> prohibited this check_in from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @check_in.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :deliverer_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :deliverer_id, :class => 'form-control' %>
    </div>
    <%= error_span(@check_in[:deliverer_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :latitude, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :latitude, :class => 'form-control' %>
    </div>
    <%= error_span(@check_in[:latitude]) %>
  </div>
  <div class="control-group">
    <%= f.label :longitude, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :longitude, :class => 'form-control' %>
    </div>
    <%= error_span(@check_in[:longitude]) %>
  </div>
  <div class="control-group">
    <%= f.label :timestamp, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :timestamp, :class => 'form-control' %>
    </div>
    <%= error_span(@check_in[:timestamp]) %>
  </div>
  <div class="control-group">
    <%= f.label :section_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :section_id, :class => 'form-control' %>
    </div>
    <%= error_span(@check_in[:section_id]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            check_ins_path, :class => 'btn btn-default' %>

<% end %>

app/views/check_ins/_sidebar.html.erb
<div class="col-lg-3">
  <div class="list-group">
    <%= link_to '<i class="fa fa-list"></i> Check-In list'.html_safe, check_ins_path, :class => "list-group-item #{'active' if action_name == 'index'}" %>
    <%= link_to '<i class="fa fa-upload"></i> Import new CSV'.html_safe, import_csv_check_ins_path, :class => "list-group-item #{'active' if action_name == 'import_csv'}" %>
     <%= link_to '<i class="fa fa-trash-o"></i> Delete all'.html_safe, delete_all_check_ins_path, :class => "list-group-item #{'active' if action_name == 'delete_all'}" %>
    <%= link_to '<i class="fa fa-globe"></i> Show on map'.html_safe, show_on_map_check_ins_path, :class => "list-group-item #{'active' if action_name == 'show_on_map'}" %>
  </div>
  <p class="pull-right text-muted small">&copy; DAMA UPC</p>
</div><!--/span-->

app/views/check_ins/delete_all.html.erb
<div class="col-lg-12">
  <ol class="breadcrumb">
    <li><%= link_to '<i class="fa fa-map-marker"></i> Check-Ins'.html_safe, check_ins_path %></li>
    <li class="active"><i class="fa fa-trash-o"></i> Delete all</li>
  </ol>
</div>


<div class="col-lg-9">
	<div class="alert alert-danger" role="alert">
			<h4>Warning!</h4>
			<p>All check-ins will be deleted! This action cannot be revoked!</p>
			<br/>
			<a>
				<%= link_to '<i class="fa fa-trash-o"></i> Delete all'.html_safe, confirm_delete_all_check_ins_path, :class => "btn btn-default", :method => :post %>
			</a>
	</div>
</div>

<%= render :partial => "sidebar" %>

app/views/check_ins/edit.html.erb
<%- model_class = CheckIn -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/check_ins/import_csv.html.erb
<div class="col-lg-12">
  <ol class="breadcrumb">
    <li><%= link_to '<i class="fa fa-map-marker"></i> Check-Ins'.html_safe, check_ins_path %></li>
    <li class="active"><i class="fa fa-upload"></i> Import new CSV</li>
  </ol>
</div>

<div class="col-lg-9">
	<div class="alert alert-danger" role="alert">
			<h4>Warning!</h4>
			<p>New data will be imported to the database!</p>
	</div>
	<%= form_tag({action: :process_csv}, multipart: true, :class => "form") do %>
		<div class="form-group">
		  <%= label :import_file, "Choose import CSV file" %>
	 		<%= file_field_tag 'checkins_csv' %>
	 	</div>
	 	<div class="form-group">
	 		<%= submit_tag 'Submit', :class => "btn btn-sm btn-primary" %>
	 		<%= link_to 'Cancel', check_ins_path, :class => "btn btn-sm btn-default" %>
	 	</div>
	<% end %>
</div>

<%= render :partial => "sidebar" %>

app/views/check_ins/index.html.erb
<div class="col-lg-12">
  <ol class="breadcrumb">
    <li class="active"><i class="fa fa-map-marker"></i> Check-Ins</li>
  </ol>
</div>

<div class="col-lg-9">
  <%- model_class = CheckIn -%>
  <%= will_paginate @check_ins, :previous_label => 'Previous', :next_label => 'Next', :renderer => BootstrapPagination::Rails %>
  <table class="table table-striped small">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:id) %></th>
        <th><%= model_class.human_attribute_name(:deliverer_id) %></th>
        <th><%= model_class.human_attribute_name(:latitude) %></th>
        <th><%= model_class.human_attribute_name(:longitude) %></th>
        <th><%= model_class.human_attribute_name(:timestamp) %></th>
        <th><%= model_class.human_attribute_name(:section_id) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @check_ins.each do |check_in| %>
        <tr>
          <td><%= link_to check_in.id, check_in_path(check_in) %></td>
          <td>
            <% if check_in.deliverer_id.blank? %>
              <i class="fa fa-truck"></i> Unknown
            <% else %>
              <%= link_to "<i class=\"fa fa-truck\"></i> #{check_in.deliverer_id.to_s}".html_safe, deliverer_path(check_in.deliverer_id) %>
            <% end %>
          </td>
          <td><%= check_in.latitude %></td>
          <td><%= check_in.longitude %></td>
          <td><%= check_in.timestamp %></td>
          <td>
            <% unless check_in.section_id.blank? %>
              <%= link_to "<i class=\"fa fa-road\"></i> #{check_in.section_id}".html_safe, section_path(check_in.section_id) %></td>
            <% end %>
          <td>
            <%= link_to "Details", check_in_path(check_in), :class => 'btn btn-default btn-xs' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @check_ins, :previous_label => 'Previous', :next_label => 'Next', :renderer => BootstrapPagination::Rails %>
</div>

<%= render :partial => "sidebar" %>

app/views/check_ins/new.html.erb
<%- model_class = CheckIn -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/check_ins/refresh_map_view.js.erb
map.removeLayer(markers);

var markers = L.markerClusterGroup();
markers.clearLayers();
var checkIns = [<%= @check_ins.collect{|check_in| "[#{check_in.latitude},#{check_in.longitude}]" }.join(", ") %>];

for (var i = 0; i < checkIns.length; i++) {
	marker = new L.marker([checkIns[i][0],checkIns[i][1]]);
	markers.addLayer(marker);
}

map.addLayer(markers);

$('\#loader').hide();

app/views/check_ins/show.html.erb
<div class="col-lg-12">
  <ol class="breadcrumb">
    <li><%= link_to '<i class="fa fa-map-marker"></i> Check-Ins'.html_safe, check_ins_path %></li>
    <li class="active">Check-In <%= @check_in.id %></li>
  </ol>
</div>

<div class="col-lg-6">
  <%- model_class = CheckIn -%>
  <table class="table table-bordered small">
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <td><%= @check_in.id %></td>
    </tr>
    <tr>
      <th><%= model_class.human_attribute_name(:deliverer_id) %></th>
        <td>
          <% if @check_in.deliverer_id.blank? %>
            <i class="fa fa-truck"></i> Unknown</td>
          <% else %>
            <%= link_to "<i class=\"fa fa-truck\"></i> #{@check_in.deliverer_id.to_s}".html_safe, deliverer_path(@check_in.deliverer_id) %>
          <% end %>
        </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:latitude) %>
      </th>
      <td>
        <%= @check_in.latitude %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:longitude) %>
      </th>
      <td>
        <%= @check_in.longitude %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:timestamp) %>
      </th>
      <td>
        <%= @check_in.timestamp %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:section_id) %>
      </th>
      <td>
        <%= link_to "<i class=\"fa fa-road\"></i> #{@check_in.section_id.to_s}".html_safe, section_path(@check_in.section_id) %>
      </td>
  </table>
</div>

<div class="col-lg-6">
  <div style="width: 100%; height: 400px; margin-bottom: 20px;"  id="map"></div>
</div>

<script type='text/javascript'>
  var map = new L.Map('map', {center: new L.LatLng(<%= @check_in.latitude %>, <%= @check_in.longitude %>), zoom: 16});
  var googleLayer = new L.Google('ROADMAP');
  map.addLayer(googleLayer);

  L.marker([<%= @check_in.latitude %>, <%= @check_in.longitude %>]).addTo(map);                     

  // zoom the map to the polyline
  map.fitBounds(polyline.getBounds());


</script>

app/views/check_ins/show_on_map.html.erb
<div class="col-lg-12">
  <ol class="breadcrumb">
    <li><%= link_to '<i class="fa fa-map-marker"></i> Check-Ins'.html_safe, check_ins_path %></li>
    <li class="active"><i class="fa fa-globe"></i> Show on map</li>
  </ol>
</div>


<div class="col-lg-9">
  <div class="row">
    <%= form_tag({action: :refresh_map_view}, :class => "form", :remote => true) do %>
      <div class='col-sm-4'>
        <div class="form-group">
          <%= label :start_date, "Start date", :class => "small" %>
          <div class="input-group date" id="from_date">
            <%= text_field_tag :start_date, nil, :class => 'form-control input-sm' %>
            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
          </div>
        </div>
      </div>

      <div class='col-sm-4'>
        <div class="form-group">
          <%= label :end_date, "End date", :class => "small" %>
          <div class="input-group date" id="to_date">
            <%= text_field_tag :end_date, nil, :class => 'form-control input-sm' %>
            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
          </div>
        </div>
      </div>
      <div class='col-sm-4'>
        <div class="form-group">
          <%= submit_tag 'Refresh', :class => "btn btn-primary btn-sm", :style => "margin-top: 24px;", :onclick => "$('\#loader').show();" %><%= image_tag "loader.gif", :hidden => true, :id => "loader", :style => "width: 30px; margin-top: 24px; margin-left: 10px;" %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div style="width: 100%; height: 400px; margin-bottom: 20px;"  id="map"></div>
  </div>
</div>

<%= render :partial => "sidebar" %>

<script type='text/javascript'>
  var map = new L.Map('map', { center: new L.LatLng(41.386842, 2.170502), 
                               zoom: 12,
                               zoomControl: false});
  L.control.zoom({
     position:'topright'
  }).addTo(map);
  var googleLayer = new L.Google('ROADMAP');
  map.addLayer(googleLayer);
  var markers = L.markerClusterGroup();
</script>

<script type="text/javascript">

  $( document ).ready(function(){

  var startDate = new Date('01/01/2014');
  var FromEndDate = new Date();
  var ToEndDate = new Date();

  $('#from_date').datepicker({
      format: "yyyy-mm-dd",
      weekStart: 1,
      startDate: '01/01/2014',
      endDate: FromEndDate, 
      autoclose: true
  })
      .on('changeDate', function(selected){
          startDate = new Date(selected.date.valueOf());
          //startDate.setDate(startDate.getDate(new Date(selected.date.valueOf())));
          $('#to_date').datepicker('setStartDate', startDate);
      }); 
  $('#to_date')
      .datepicker({
          format: "yyyy-mm-dd",
          weekStart: 1,
          startDate: startDate,
          endDate: ToEndDate,
          autoclose: true
      })
      .on('changeDate', function(selected){
          FromEndDate = new Date(selected.date.valueOf());
          //FromEndDate.setDate(FromEndDate.getDate(new Date(selected.date.valueOf())));
          $('#from_date').datepicker('setEndDate', FromEndDate);
      });
  });
</script>