config/routes.rb
Rails.application.routes.draw do

  resources :deliverers do
    member do
      post 'refresh_map_view'
    end
  end
  devise_for :users
  root 'check_ins#index'

  resources :check_ins do
    collection do
      get 'import_csv'
      post 'process_csv'
      get 'delete_all'
      post 'confirm_delete_all'
      get 'show_on_map'
      post 'refresh_map_view'
    end
  end
  resources :sections do
    collection do
      get 'import_csv'
      post 'process_csv'
      get 'delete_all'
      post 'confirm_delete_all'
    end
    member do
      get 'show_per_time_slot'
      post 'refresh_per_time_slot'
      get 'show_per_day_of_week'
      post 'refresh_per_day_of_week'
      get 'show_avg_per_time_slot'
      post 'refresh_avg_per_time_slot'
      get 'show_avg_per_day_of_week'
      post 'refresh_avg_per_day_of_week'
      get 'show_check_ins_time_series'
      post 'refresh_check_ins_time_series'
      get 'download_csv_reports'
    end
  end
  resources :section_configurations do
    collection do
      get 'import_csv'
      post 'process_csv'
      get 'delete_all'
      post 'confirm_delete_all'
    end
  end

end

app/models/section.rb
class Section < ActiveRecord::Base
	has_many :check_ins
	belongs_to :section_configuration
	belongs_to :street
	belongs_to :district
	belongs_to :neighbourhood
end

app/controllers/sections_controller.rb
require 'csv'
require 'statistic_queries'

class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :show_per_time_slot, :refresh_per_time_slot, :show_per_day_of_week, 
                                     :refresh_per_day_of_week, :show_avg_per_time_slot, :refresh_avg_per_time_slot, 
                                     :show_avg_per_day_of_week, :refresh_avg_per_day_of_week, :download_csv_reports,
                                     :show_check_ins_time_series, :refresh_check_ins_time_series,
                                     :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all.paginate(:page => params[:page], :per_page => 100)
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  def show_per_time_slot
    @max_datetime = CheckIn.where(:section_id => @section.id).maximum(:timestamp)
    @min_datetime = CheckIn.where(:section_id => @section.id).minimum(:timestamp)
    @stats = StatisticQueries::Sections::total_check_ins_per_time_slot(@section, @min_datetime, @max_datetime, 30, [1,2,3,4,5]).to_a
  end

  def refresh_per_time_slot
    time_slot_size = params[:time_slot_size].to_i
    days_of_week = params[:day_of_week].split(",").map(&:to_i)
    @plot_type = params[:plot_type].to_i
    if !params[:start_date].blank? && !params[:end_date].blank?
      start_date = Date.strptime(params[:start_date], '%Y-%m-%d')
      end_date = Date.strptime(params[:end_date], '%Y-%m-%d')
      @stats = StatisticQueries::Sections::total_check_ins_per_time_slot(@section, start_date, end_date, time_slot_size, days_of_week).to_a
    else
      @max_datetime = CheckIn.where(:section_id => @section.id).maximum(:timestamp)
      @min_datetime = CheckIn.where(:section_id => @section.id).minimum(:timestamp)
      @stats = StatisticQueries::Sections::total_check_ins_per_time_slot(@section, @min_datetime, @max_datetime, time_slot_size, days_of_week).to_a
    end

  end

  def show_per_day_of_week
    @max_datetime = CheckIn.where(:section_id => @section.id).maximum(:timestamp)
    @min_datetime = CheckIn.where(:section_id => @section.id).minimum(:timestamp)
    @stats = StatisticQueries::Sections::total_check_ins_per_day_of_week(@section, @min_datetime, @max_datetime).to_a
  end

  def refresh_per_day_of_week
    @plot_type = params[:plot_type].to_i
    if !params[:start_date].blank? && !params[:end_date].blank?
      start_date = Date.strptime(params[:start_date], '%Y-%m-%d')
      end_date = Date.strptime(params[:end_date], '%Y-%m-%d')
      @stats = StatisticQueries::Sections::total_check_ins_per_day_of_week(@section, start_date, end_date).to_a
    else
      @max_datetime = CheckIn.where(:section_id => @section.id).maximum(:timestamp)
      @min_datetime = CheckIn.where(:section_id => @section.id).minimum(:timestamp)
      @stats = StatisticQueries::Sections::total_check_ins_per_day_of_week(@section, @min_datetime, @max_datetime).to_a
    end
  end

  def show_avg_per_time_slot
    @max_datetime = CheckIn.where(:section_id => @section.id).maximum(:timestamp)
    @min_datetime = CheckIn.where(:section_id => @section.id).minimum(:timestamp)
    @stats = StatisticQueries::Sections::avg_check_ins_per_time_slot(@section, @min_datetime, @max_datetime, 30, [1,2,3,4,5]).to_a
  end

  def refresh_avg_per_time_slot
    days_of_week = params[:day_of_week].split(",").map(&:to_i)
    time_slot_size = params[:time_slot_size].to_i
    if !params[:start_date].blank? && !params[:end_date].blank?
      start_date = Date.strptime(params[:start_date], '%Y-%m-%d')
      end_date = Date.strptime(params[:end_date], '%Y-%m-%d')
      @stats = StatisticQueries::Sections::avg_check_ins_per_time_slot(@section, start_date, end_date, time_slot_size, days_of_week).to_a
    else
      @max_datetime = CheckIn.where(:section_id => @section.id).maximum(:timestamp)
      @min_datetime = CheckIn.where(:section_id => @section.id).minimum(:timestamp)
      @stats = StatisticQueries::Sections::avg_check_ins_per_time_slot(@section, @min_datetime, @max_datetime, time_slot_size, days_of_week).to_a
    end
  end

  def show_avg_per_day_of_week
    @max_datetime = CheckIn.where(:section_id => @section.id).maximum(:timestamp)
    @min_datetime = CheckIn.where(:section_id => @section.id).minimum(:timestamp)
    @stats = StatisticQueries::Sections::avg_check_ins_per_day_of_week(@section, @min_datetime, @max_datetime).to_a
  end

  def refresh_avg_per_day_of_week
    if !params[:start_date].blank? && !params[:end_date].blank?
      start_date = Date.strptime(params[:start_date], '%Y-%m-%d')
      end_date = Date.strptime(params[:end_date], '%Y-%m-%d')
      @stats = StatisticQueries::Sections::avg_check_ins_per_day_of_week(@section, start_date, end_date).to_a
    else
      @max_datetime = CheckIn.where(:section_id => @section.id).maximum(:timestamp)
      @min_datetime = CheckIn.where(:section_id => @section.id).minimum(:timestamp)
      @stats = StatisticQueries::Sections::avg_check_ins_per_day_of_week(@section, @min_datetime, @max_datetime).to_a
    end
  end

  def show_check_ins_time_series
    @max_datetime = CheckIn.where(:section_id => @section.id).maximum(:timestamp)
    @min_datetime = CheckIn.where(:section_id => @section.id).minimum(:timestamp)
    @stats = StatisticQueries::Sections::check_ins_time_series(@section, @min_datetime, @max_datetime, 30).to_a
  end

  def refresh_check_ins_time_series
    time_slot_size = params[:time_slot_size].to_i
    if !params[:start_date].blank? && !params[:end_date].blank?
      start_date = Date.strptime(params[:start_date], '%Y-%m-%d')
      end_date = Date.strptime(params[:end_date], '%Y-%m-%d')
      @stats = StatisticQueries::Sections::check_ins_time_series(@section, start_date, end_date, time_slot_size).to_a
    else
      @max_datetime = CheckIn.where(:section_id => @section.id).maximum(:timestamp)
      @min_datetime = CheckIn.where(:section_id => @section.id).minimum(:timestamp)
      @stats = StatisticQueries::Sections::check_ins_time_series(@section, @min_datetime, @max_datetime, time_slot_size).to_a
    end
  end

  def download_csv_reports
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import_csv
  end

  def process_csv
    uploaded_file = params[:sections_csv]
    batch,batch_size = [], 1_000 
    CSV.foreach(uploaded_file.path, headers: true, encoding:'iso-8859-1:utf-8') do |row|

      new_section = Section.new(:latitude => 0.0,
                                :longitude => 0.0,
                                :dum_zone_id => row[2].to_i,
                                :section_name => row[3],
                                :street_id => row[4].to_i,
                                :street_no => row[5].to_i,
                                :section_type_id => row[6].to_i,
                                :authorized_spaces => row[7].to_i,
                                :unavailable_spaces => row[8].to_i,
                                :available_spaces => row[9].to_i,
                                :section_configuration_id => row[10].to_i,
                                # District IDs not mach open data uless
                                :district_id => row[11].to_i - 1,
                                :neighbourhood_id => row[12].to_i,
                                :regulatory_zone_id => row[13].to_i)

      if row[0] == "30-4-2015 00:00:00"
        new_section.id = row[1].to_i
        batch << new_section
      end

      if batch.size >= batch_size
        Section.import batch
        batch = []
      end
    end
    Section.import batch

    redirect_to :action => :index
  end

  def delete_all
  end

  def confirm_delete_all
    Section.delete_all
    redirect_to :action => :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.fetch(:section, {})
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_show_table_details.html.erb
<%- model_class = Section -%>
<table class="table table-bordered small">
  <tr>
    <th>
      <%= model_class.human_attribute_name(:id) %>
    </th>
    <td>
      <%= @section.id %>
    </td>
  </tr>
  <tr>
    <th>
      <%= model_class.human_attribute_name(:latitude) %>
    </th>
    <td class="<%= 'danger' if @section.latitude == 0.0 %>">
      <span class="<%= 'text-danger' if @section.latitude == 0.0 %>"><%= @section.latitude %></span>
    </td>
  </tr>
  <tr>
    <th>
      <%= model_class.human_attribute_name(:longitude) %>
    </th>
    <td class="<%= 'danger' if @section.longitude == 0.0 %>">
      <span class="<%= 'text-danger' if @section.longitude == 0.0 %>"><%= @section.longitude %></span>
    </td>
  </tr>
  <tr>
    <th>
      <%= model_class.human_attribute_name(:dum_zone_id) %>
    </th>
    <td>
      <%= @section.dum_zone_id %>
    </td>
  </tr>
  <tr>
    <th>
      <%= model_class.human_attribute_name(:section_name) %>
    </th>
    <td>
      <i><%= @section.section_name %></i>
    </td>
  </tr>
  <tr>
    <th>
      <%= model_class.human_attribute_name(:street_id) %>
    </th>
    <td>
      <%= @section.street.official_name %>
    </td>
  </tr>
  <tr>
    <th>
      <%= model_class.human_attribute_name(:street_no) %>
    </th>
    <td>
      <%= @section.street_no %>
    </td>
  </tr>
  <tr>
    <th>
      <%= model_class.human_attribute_name(:section_type_id) %>
    </th>
    <td>
      <%= @section.section_type_id %>
    </td>
  </tr>
  <tr>
    <th>
      <%= model_class.human_attribute_name(:available_spaces) %>
    </th>
    <td>
      <% @section.authorized_spaces.times do |sp|  %>
        <span class="fa-stack small <%= sp < @section.available_spaces ? "text-primary" : "text-danger" %>">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-truck fa-stack-1x"></i>
        </span>
      <% end %> (<%= @section.available_spaces %>/<%= @section.authorized_spaces %>)
    </td>
  </tr>
  <tr>
    <th>
      <%= model_class.human_attribute_name(:section_configuration_id) %>
    </th>
    <td>
      <%= link_to "<i class=\"fa fa-cogs\"></i> Configuration #{@section.section_configuration_id}".html_safe, section_configuration_path(@section.section_configuration_id) %>
    </td>
  </tr>
  <tr>
    <th>
      <%= model_class.human_attribute_name(:district_id) %>
    </th>
    <td>
      <%= @section.district.name %>
    </td>
  </tr>
  <tr>
    <th>
      <%= model_class.human_attribute_name(:neighbourhood_id) %>
    </th>
    <td>
      <%= @section.neighbourhood.name %>
    </td>
  </tr>
  <tr>
    <th>
      <%= model_class.human_attribute_name(:regulatory_zone_id) %>
    </th>
    <td>
      <%= @section.regulatory_zone_id %>
    </td>
  </tr>
 <!-- <tr>
    <th>
      Total working day check-ins
    </th>
    <td class="active">
      <%= @check_in_count %>
    </td>
  </tr>
  <tr>
    <th>
      Total weekend day check-ins
    </th>
    <td class="active">
      <%= @check_in_count_weekend %>
    </td>
  </tr>     -->
</table>

app/views/sections/_show_tabs.html.erb
<ul class="nav nav-tabs" style="margin-bottom: 30px;">
  <li role="presentation" class="<%= 'active' if controller_name == 'sections' && action_name == 'show' %>"><%= link_to '<i class="fa fa-globe"></i> Map'.html_safe, @section %></li>


  
  <li class="dropdown <%= 'active' if controller_name == 'sections' && (action_name == 'show_per_time_slot' || action_name == 'show_per_day_of_week' || action_name == 'show_avg_per_time_slot' || action_name == 'show_avg_per_day_of_week' || action_name == 'show_check_ins_time_series') %>">
    <a href="#" data-toggle="dropdown"><i class="fa fa-bar-chart-o"></i> Plots <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
		  <li role="presentation" class="<%= 'active' if controller_name == 'sections' && action_name == 'show_per_time_slot' %>"><%= link_to '<b>Total number of check-ins</b> per time slots'.html_safe, show_per_time_slot_section_path(@section) %></li>
		  <li role="presentation" class="<%= 'active' if controller_name == 'sections' && action_name == 'show_per_day_of_week' %>"><%= link_to '<b>Total number of check-ins</b> per day of week'.html_safe, show_per_day_of_week_section_path(@section) %></li>
      
      <li role="presentation" class="divider"></li>

      <li role="presentation" class="<%= 'active' if controller_name == 'sections' && action_name == 'show_avg_per_time_slot' %>"><%= link_to '<b>Average number of check-ins</b> per time slots'.html_safe, show_avg_per_time_slot_section_path(@section) %></li>
      <li role="presentation" class="<%= 'active' if controller_name == 'sections' && action_name == 'show_avg_per_day_of_week' %>"><%= link_to '<b>Average number of check-ins</b> per day of week'.html_safe, show_avg_per_day_of_week_section_path(@section) %></li>

      <li role="presentation" class="divider"></li>

		  <li role="presentation" class="<%= 'active' if controller_name == 'sections' && action_name == 'show_check_ins_time_series' %>"><%= link_to 'Check-ins as <b>time series</b>'.html_safe, show_check_ins_time_series_section_path(@section) %></li>
    </ul>
  </li>
  <li class="nav-divider"></li>
  <li role="presentation" class="<%= 'active' if controller_name == 'sections' && action_name == 'download_csv_reports' %>"><%= link_to '<i class="fa fa-download"></i> Download CSV reports'.html_safe, download_csv_reports_section_path(@section) %></li>
</ul>

app/views/sections/_sidebar.html.erb
<div class="col-lg-3">
  <div class="list-group">
    <%= link_to '<i class="fa fa-list"></i> Section list'.html_safe, sections_path, :class => "list-group-item #{'active' if action_name == 'index'}" %>
    <%= link_to '<i class="fa fa-upload"></i> Import new CSV'.html_safe, import_csv_sections_path, :class => "list-group-item #{'active' if action_name == 'import_csv'}" %>
     <%= link_to '<i class="fa fa-trash-o"></i> Delete all'.html_safe, delete_all_sections_path, :class => "list-group-item #{'active' if action_name == 'delete_all'}" %>
  </div>
  <p class="pull-right text-muted small">&copy; DAMA UPC</p>
</div><!--/span-->

app/views/sections/delete_all.html.erb
<div class="col-lg-12">
  <ol class="breadcrumb">
    <li><%= link_to '<i class="fa fa-road"></i> Sections'.html_safe, sections_path %></li>
    <li class="active"><i class="fa fa-trash-o"></i> Delete all</li>
  </ol>
</div>


<div class="col-lg-9">
	<div class="alert alert-danger" role="alert">
			<h4>Warning!</h4>
			<p>All sections will be deleted! This action cannot be revoked!</p>
			<br/>
			<a>
				<%= link_to '<i class="fa fa-trash-o"></i> Delete all'.html_safe, confirm_delete_all_sections_path, :class => "btn btn-default", :method => :post %>
			</a>
	</div>
</div>

<%= render :partial => "sidebar" %>

app/views/sections/import_csv.html.erb
<div class="col-lg-12">
  <ol class="breadcrumb">
    <li><%= link_to '<i class="fa fa-road"></i> Sections'.html_safe, sections_path %></li>
    <li class="active"><i class="fa fa-upload"></i> Import new CSV</li>
  </ol>
</div>

<div class="col-lg-9">
	<div class="alert alert-danger" role="alert">
			<h4>Warning!</h4>
			<p>New data will be imported to the database. Existing data can be overwritten!</p>
	</div>
	<%= form_tag({action: :process_csv}, multipart: true, :class => "form") do %>
		<div class="form-group">
		  <%= label :import_file, "Choose import CSV file" %>
	 		<%= file_field_tag 'sections_csv' %>
	 	</div>
	 	<div class="form-group">
	 		<%= submit_tag 'Submit', :class => "btn btn-sm btn-primary" %>
	 		<%= link_to 'Cancel', sections_path, :class => "btn btn-sm btn-default" %>
	 	</div>
	<% end %>
</div>

<%= render :partial => "sidebar" %>

app/views/sections/index.html.erb
<div class="col-lg-12">
  <ol class="breadcrumb">
    <li class="active"><i class="fa fa-road"></i> Sections</li>
  </ol>
</div>

<div class="col-lg-9">
  <%- model_class = Section -%>
  <%= will_paginate @sections, :previous_label => 'Previous', :next_label => 'Next', :renderer => BootstrapPagination::Rails %>
  <table class="table table-striped small">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:section_name) %></th>
        <th><%= model_class.human_attribute_name(:latitude) %></th>
        <th><%= model_class.human_attribute_name(:longitude) %></th>
        <th><%= model_class.human_attribute_name(:available_spaces) %></th>
        <th><%= model_class.human_attribute_name(:district) %></th>
        <th><%= model_class.human_attribute_name(:neighbourhood) %></th>
        <th><%= model_class.human_attribute_name(:section_configuration_id) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @sections.each do |section| %>
        <tr>
          <td><%= link_to section.section_name, section_path(section) %></td>
          <td><span class="<%= 'text-danger' if section.latitude == 0.0 %>"><%= section.latitude %></span></td>
          <td><span class="<%= 'text-danger' if section.longitude == 0.0 %>"><%= section.longitude %></span></td>
          <td>
            <b><%= section.available_spaces %>/<%= section.authorized_spaces %></b>
          </td>
          <td><%= section.district.name %></td>
          <td><%= section.neighbourhood.name %></td>
          <td><%= link_to "<i class=\"fa fa-cogs\"></i> Configuration #{section.section_configuration_id}".html_safe, section_configuration_path(section.section_configuration_id) %></td>
          <td>
            <%= link_to "Details", section_path(section), :class => 'btn btn-default btn-xs' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @sections, :previous_label => 'Previous', :next_label => 'Next', :renderer => BootstrapPagination::Rails %>
</div>

<%= render :partial => "sidebar" %>

app/views/sections/new.html.erb
<%- model_class = Section -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sections/show.html.erb
<div class="col-lg-12">
  <ol class="breadcrumb">
    <li><%= link_to '<i class="fa fa-road"></i> Sections'.html_safe, sections_path %></li>
    <li class="active"><i class="fa fa-globe"></i> <%= @section.section_name %></li>
  </ol>
  <%= render :partial => 'show_tabs' %>
</div>

<div class="col-lg-4">
  <%= render :partial => "show_table_details" %>
</div>

<div class="col-lg-8">
  <div style="width: 100%; height: 472px;"  id="map"></div>
</div>

<script type='text/javascript'>
  var center = new L.LatLng(41.386842, 2.170502);
  <% if @section.latitude != 0.0 && @section.longitude != 0.0 %>
    center = new L.LatLng(<%= @section.latitude %>, <%= @section.longitude %>);
  <% end %>
  var map = new L.Map('map', {  center: center, 
                                zoom: 16,
                                zoomControl: false
  });
  L.control.zoom({
     position:'topright'
  }).addTo(map);
  var googleLayer = new L.Google('ROADMAP');
  map.addLayer(googleLayer);
  <% if @section.latitude != 0.0 && @section.longitude != 0.0 %>
    var marker = L.marker([<%= @section.latitude %>, <%= @section.longitude %>]).addTo(map);
  <% end %>
</script>

app/views/sections/show_avg_per_day_of_week.html.erb
<div class="col-lg-12">
  <ol class="breadcrumb">
    <li><%= link_to '<i class="fa fa-road"></i> Sections'.html_safe, sections_path %></li>
    <li><%= link_to "<i class=\"fa fa-globe\"></i> #{@section.section_name}".html_safe, @section %></li>
    <li class="active"><i class="fa fa-bar-chart-o"></i> Average number of check-ins per day of week</li>
  </ol>
  <%= render :partial => 'show_tabs' %>
  <%= form_tag({action: :refresh_avg_per_day_of_week}, :class => "form", :remote => true) do %>
    <div class='col-sm-3'>
      <div class="form-group">
        <%= label :start_date, "Start date", :class => "small" %>
        <div class="input-group date" id="from_date">
          <%= text_field_tag :start_date, nil, :class => 'form-control input-sm' %>
          <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
        </div>
      </div>
    </div>

    <div class='col-sm-3'>
      <div class="form-group">
        <%= label :end_date, "End date", :class => "small" %>
        <div class="input-group date" id="to_date">
          <%= text_field_tag :end_date, nil, :class => 'form-control input-sm' %>
          <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
        </div>
      </div>
    </div>
    <div class='col-sm-6'>
      <div class="form-group">
        <%= button_tag(:type => "submit", :class => "btn btn-sm btn-primary", :style => "margin-top: 24px;", :onclick => "$('\#loader').show();") do %>
          <i class="fa fa-refresh"></i> Refresh
        <% end %>
        <%= image_tag "loader.gif", :hidden => true, :id => "loader", :style => "width: 30px; margin-top: 24px; margin-left: 10px;" %>
      </div>
    </div>
  <% end %>

  <canvas id="chart" height="110"></canvas>
</div>

<script type="text/javascript">
  $(document).ready(function(){

  var startDate = new Date('2014-01-01');
  var FromEndDate = new Date();
  var ToEndDate = new Date();

  $('#from_date').datepicker({
      format: "yyyy-mm-dd",
      weekStart: 1,
      startDate: '2014-01-01',
      endDate: FromEndDate, 
      setDate: new Date('<%= @min_datetime.strftime('%Y-%m-%d') %>'),
      autoclose: true
  })
      .on('changeDate', function(selected){
          startDate = new Date(selected.date.valueOf());
          $('#to_date').datepicker('setStartDate', startDate);
      }); 
  $('#to_date')
      .datepicker({
          format: "yyyy-mm-dd",
          weekStart: 1,
          startDate: startDate,
          endDate: ToEndDate,
          autoclose: true
      })
      .on('changeDate', function(selected){
          FromEndDate = new Date(selected.date.valueOf());
          $('#from_date').datepicker('setEndDate', FromEndDate);
      });

  $('#from_date').datepicker("setDate", new Date('<%= @min_datetime.strftime('%Y-%m-%d') %>'));
  $('#to_date').datepicker("setDate", new Date('<%= @max_datetime.strftime('%Y-%m-%d') %>'));

  });

  var data = {
    labels: [<%= @stats.collect{|row| "'#{row['day_name']}'"}.join(", ").html_safe %>],
    datasets: [
        {
          label: "mean",
          fill: false,
          backgroundColor: "rgba(75,192,192,0.4)",
          borderColor: "rgba(75,192,192,1)",
          pointBorderColor: "rgba(75,192,192,1)",
          pointBackgroundColor: "#fff",
          pointBorderWidth: 1,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: "rgba(75,192,192,1)",
          pointHoverBorderColor: "rgba(220,220,220,1)",
          pointHoverBorderWidth: 2,
          data: [<%= @stats.collect{|row| "#{row['mean'].to_f.round(4)}"}.join(", ").html_safe %>]
        },
        {
          label: "mean+stdv",
          fill: false,
          backgroundColor: "rgba(75,192,192,0.4)",
          borderColor: "rgba(75,192,192,1)",
          pointBorderColor: "rgba(75,192,192,1)",
          borderWidth: 1,
          borderDash: [5,3],
          pointBackgroundColor: "#fff",
          pointBorderWidth: 1,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: "rgba(75,192,192,1)",
          pointHoverBorderColor: "rgba(220,220,220,1)",
          pointHoverBorderWidth: 2,
          data: [<%= @stats.collect{|row| "#{(row['mean'].to_f + row['stdev'].to_f).round(4)}"}.join(", ").html_safe %>]
        },
        {
          label: "mean-stdv",
          fill: false,
          backgroundColor: "rgba(75,192,192,0.4)",
          borderColor: "rgba(75,192,192,1)",
          pointBorderColor: "rgba(75,192,192,1)",
          borderWidth: 1,
          borderDash: [5,3],
          pointBackgroundColor: "#fff",
          pointBorderWidth: 1,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: "rgba(75,192,192,1)",
          pointHoverBorderColor: "rgba(220,220,220,1)",
          pointHoverBorderWidth: 2,
          data: [<%= @stats.collect{|row| "#{(row['mean'].to_f - row['stdev'].to_f) < 0.0 ? 0.0 : (row['mean'].to_f - row['stdev'].to_f).round(4)}"}.join(", ").html_safe %>]
        }
    ]
  };

  var ctx = $("#chart");
  var myLineChart = new Chart(ctx, {
    type: 'line',
    data: data
  });


</script>