config/routes.rb
Rails.application.routes.draw do

  resources :deliverers do
    member do
      post 'refresh_map_view'
    end
  end
  devise_for :users
  root 'check_ins#index'

  resources :check_ins do
    collection do
      get 'import_csv'
      post 'process_csv'
      get 'delete_all'
      post 'confirm_delete_all'
      get 'show_on_map'
      post 'refresh_map_view'
    end
  end
  resources :sections do
    collection do
      get 'import_csv'
      post 'process_csv'
      get 'delete_all'
      post 'confirm_delete_all'
    end
    member do
      get 'show_per_time_slot'
      post 'refresh_per_time_slot'
      get 'show_per_day_of_week'
      post 'refresh_per_day_of_week'
      get 'show_avg_per_time_slot'
      post 'refresh_avg_per_time_slot'
      get 'show_avg_per_day_of_week'
      post 'refresh_avg_per_day_of_week'
      get 'show_check_ins_time_series'
      post 'refresh_check_ins_time_series'
      get 'download_csv_reports'
    end
  end
  resources :section_configurations do
    collection do
      get 'import_csv'
      post 'process_csv'
      get 'delete_all'
      post 'confirm_delete_all'
    end
  end

end

app/models/section_configuration.rb
class SectionConfiguration < ActiveRecord::Base
	has_many :sections
end

app/controllers/section_configurations_controller.rb
require 'csv'

class SectionConfigurationsController < ApplicationController
  before_action :set_section_configuration, only: [:show, :edit, :update, :destroy]

  # GET /section_configurations
  # GET /section_configurations.json
  def index
    @section_configurations = SectionConfiguration.all.sort
  end

  # GET /section_configurations/1
  # GET /section_configurations/1.json
  def show
  end

  # GET /section_configurations/new
  def new
    @section_configuration = SectionConfiguration.new
  end

  # GET /section_configurations/1/edit
  def edit
  end

  # POST /section_configurations
  # POST /section_configurations.json
  def create
    @section_configuration = SectionConfiguration.new(section_configuration_params)

    respond_to do |format|
      if @section_configuration.save
        format.html { redirect_to @section_configuration, notice: 'Section configuration was successfully created.' }
        format.json { render :show, status: :created, location: @section_configuration }
      else
        format.html { render :new }
        format.json { render json: @section_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /section_configurations/1
  # PATCH/PUT /section_configurations/1.json
  def update
    respond_to do |format|
      if @section_configuration.update(section_configuration_params)
        format.html { redirect_to @section_configuration, notice: 'Section configuration was successfully updated.' }
        format.json { render :show, status: :ok, location: @section_configuration }
      else
        format.html { render :edit }
        format.json { render json: @section_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /section_configurations/1
  # DELETE /section_configurations/1.json
  def destroy
    @section_configuration.destroy
    respond_to do |format|
      format.html { redirect_to section_configurations_url, notice: 'Section configuration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import_csv
  end

  def process_csv
    uploaded_file = params[:configurations_csv]
    batch,batch_size = [], 1_000 
    CSV.foreach(uploaded_file.path, headers: true, encoding:'iso-8859-1:utf-8') do |row|
      new_configuration = SectionConfiguration.new(:tariff_id => row[1].to_i,
                                                   :schedule_id => row[2].to_i,
                                                   :configuration_type_id => row[3].to_i,
                                                   :color_desc => row[4].to_s,
                                                   :color_desc_pda => row[5].to_s,
                                                   :configuration_code => row[6].to_s,
                                                   :active => row[7].to_i == 1 ? true : false,
                                                   :tariff_code => row[8].to_s,
                                                   :schedule_code => row[9].to_s,
                                                   :configuration_type_code => row[10].to_s,
                                                   :description => row[11].to_s,
                                                   :tarrif_description_short => row[12].to_s,
                                                   :schedule_description_short => row[13].to_s,
                                                   :include_holidays => row[14].to_i == 1 ? true : false,
                                                   :only_parking => row[15].to_i == 1 ? true : false,
                                                   :fraction_type => row[16].to_i,
                                                   :fraction_price => row[17].to_i,
                                                   :max_time => row[18].to_f,
                                                   :price_per_hour => row[19].to_f,
                                                   :price_per_minute => row[20].to_f,
                                                   :price_per_second => row[21].to_f)
      new_configuration.id = row[0].to_i
      batch << new_configuration

      if batch.size >= batch_size
        SectionConfiguration.import batch
        batch = []
      end
    end
    SectionConfiguration.import batch

    redirect_to :action => :index
  end

  def delete_all
  end

  def confirm_delete_all
    SectionConfiguration.delete_all
    redirect_to :action => :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section_configuration
      @section_configuration = SectionConfiguration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_configuration_params
      params.fetch(:section_configuration, {})
    end
end

app/helpers/section_configurations_helper.rb
module SectionConfigurationsHelper
end

app/views/section_configurations/_form.html.erb
<%= form_for @section_configuration, :html => { :class => "form-horizontal section_configuration" } do |f| %>

    <% if @section_configuration.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@section_configuration.errors.count, "error") %> prohibited this section_configuration from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @section_configuration.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :tariff_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tariff_id, :class => 'form-control' %>
    </div>
    <%= error_span(@section_configuration[:tariff_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :schedule_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :schedule_id, :class => 'form-control' %>
    </div>
    <%= error_span(@section_configuration[:schedule_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :configuration_type_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :configuration_type_id, :class => 'form-control' %>
    </div>
    <%= error_span(@section_configuration[:configuration_type_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :color_desc, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :color_desc, :class => 'form-control' %>
    </div>
    <%= error_span(@section_configuration[:color_desc]) %>
  </div>
  <div class="control-group">
    <%= f.label :color_desc_pda, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :color_desc_pda, :class => 'form-control' %>
    </div>
    <%= error_span(@section_configuration[:color_desc_pda]) %>
  </div>
  <div class="control-group">
    <%= f.label :configuration_code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :configuration_code, :class => 'form-control' %>
    </div>
    <%= error_span(@section_configuration[:configuration_code]) %>
  </div>
  <div class="control-group">
    <%= f.label :active, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :active, :class => 'form-control' %>
    </div>
    <%= error_span(@section_configuration[:active]) %>
  </div>
  <div class="control-group">
    <%= f.label :tariff_code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tariff_code, :class => 'form-control' %>
    </div>
    <%= error_span(@section_configuration[:tariff_code]) %>
  </div>
  <div class="control-group">
    <%= f.label :schedule_code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :schedule_code, :class => 'form-control' %>
    </div>
    <%= error_span(@section_configuration[:schedule_code]) %>
  </div>
  <div class="control-group">
    <%= f.label :configuration_type_code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :configuration_type_code, :class => 'form-control' %>
    </div>
    <%= error_span(@section_configuration[:configuration_type_code]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@section_configuration[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :tarrif_description_short, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tarrif_description_short, :class => 'form-control' %>
    </div>
    <%= error_span(@section_configuration[:tarrif_description_short]) %>
  </div>
  <div class="control-group">
    <%= f.label :schedule_description_short, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :schedule_description_short, :class => 'form-control' %>
    </div>
    <%= error_span(@section_configuration[:schedule_description_short]) %>
  </div>
  <div class="control-group">
    <%= f.label :include_holidays, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :include_holidays, :class => 'form-control' %>
    </div>
    <%= error_span(@section_configuration[:include_holidays]) %>
  </div>
  <div class="control-group">
    <%= f.label :only_parking, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :only_parking, :class => 'form-control' %>
    </div>
    <%= error_span(@section_configuration[:only_parking]) %>
  </div>
  <div class="control-group">
    <%= f.label :fraction_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :fraction_type, :class => 'form-control' %>
    </div>
    <%= error_span(@section_configuration[:fraction_type]) %>
  </div>
  <div class="control-group">
    <%= f.label :fraction_price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :fraction_price, :class => 'form-control' %>
    </div>
    <%= error_span(@section_configuration[:fraction_price]) %>
  </div>
  <div class="control-group">
    <%= f.label :max_time, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :max_time, :class => 'form-control' %>
    </div>
    <%= error_span(@section_configuration[:max_time]) %>
  </div>
  <div class="control-group">
    <%= f.label :price_per_hour, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price_per_hour, :class => 'form-control' %>
    </div>
    <%= error_span(@section_configuration[:price_per_hour]) %>
  </div>
  <div class="control-group">
    <%= f.label :price_per_minute, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price_per_minute, :class => 'form-control' %>
    </div>
    <%= error_span(@section_configuration[:price_per_minute]) %>
  </div>
  <div class="control-group">
    <%= f.label :price_per_second, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price_per_second, :class => 'form-control' %>
    </div>
    <%= error_span(@section_configuration[:price_per_second]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            section_configurations_path, :class => 'btn btn-default' %>

<% end %>

app/views/section_configurations/_sidebar.html.erb
<div class="col-lg-3">
  <div class="list-group">
    <%= link_to '<i class="fa fa-list"></i> Configuration list'.html_safe, section_configurations_path, :class => "list-group-item #{'active' if action_name == 'index'}" %>
    <%= link_to '<i class="fa fa-upload"></i> Import new CSV'.html_safe, import_csv_section_configurations_path, :class => "list-group-item #{'active' if action_name == 'import_csv'}" %>
     <%= link_to '<i class="fa fa-trash-o"></i> Delete all'.html_safe, delete_all_section_configurations_path, :class => "list-group-item #{'active' if action_name == 'delete_all'}" %>
  </div>
  <p class="pull-right text-muted small">&copy; DAMA UPC</p>
</div><!--/span-->

app/views/section_configurations/delete_all.html.erb
<div class="col-lg-12">
  <ol class="breadcrumb">
    <li><%= link_to '<i class="fa fa-cogs"></i> Section Configurations'.html_safe, section_configurations_path %></li>
    <li class="active"><i class="fa fa-trash-o"></i> Delete all</li>
  </ol>
</div>

<div class="col-lg-9">
	<div class="alert alert-danger" role="alert">
			<h4>Warning!</h4>
			<p>All section configuration will be deleted! This action cannot be revoked!</p>
			<br/>
			<a>
				<%= link_to '<i class="fa fa-trash-o"></i> Delete all'.html_safe, confirm_delete_all_section_configurations_path, :class => "btn btn-default", :method => :post %>
			</a>
	</div>
</div>

<%= render :partial => "sidebar" %>

app/views/section_configurations/edit.html.erb
<%- model_class = SectionConfiguration -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/section_configurations/import_csv.html.erb
<div class="col-lg-12">
  <ol class="breadcrumb">
    <li><%= link_to '<i class="fa fa-cogs"></i> Section Configurations'.html_safe, section_configurations_path %></li>
    <li class="active"><i class="fa fa-upload"></i> Import new CSV</li>
  </ol>
</div>


<div class="col-lg-9">
	<div class="alert alert-danger" role="alert">
			<h4>Warning!</h4>
			<p>New data will be imported to the database. Existing data can be overwritten!</p>
	</div>
	<%= form_tag({action: :process_csv}, multipart: true, :class => "form") do %>
		<div class="form-group">
		  <%= label :import_file, "Choose import CSV file" %>
	 		<%= file_field_tag 'configurations_csv' %>
	 	</div>
	 	<div class="form-group">
	 		<%= submit_tag 'Submit', :class => "btn btn-sm btn-primary" %>
	 		<%= link_to 'Cancel', section_configurations_path, :class => "btn btn-sm btn-default" %>
	 	</div>
	<% end %>
</div>

<%= render :partial => "sidebar" %>

app/views/section_configurations/index.html.erb
<div class="col-lg-12">
  <ol class="breadcrumb">
    <li class="active"><i class="fa fa-cogs"></i> Section Configurations</li>
  </ol>
</div>

<div class="col-lg-9">
  <%- model_class = SectionConfiguration -%>
  <table class="table table-striped small">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:id) %></th>
        <th><%= model_class.human_attribute_name(:color_desc) %></th>
        <th><%= model_class.human_attribute_name(:configuration_code) %></th>
        <th><%= model_class.human_attribute_name(:active) %></th>
        <th><%= model_class.human_attribute_name(:tariff_code) %></th>
        <th><%= model_class.human_attribute_name(:schedule_code) %></th>
        <th><%= model_class.human_attribute_name(:configuration_type_code) %></th>
        <th><%= model_class.human_attribute_name(:description) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @section_configurations.each do |section_configuration| %>
        <tr>
          <td><%= link_to section_configuration.id, section_configuration_path(section_configuration) %></td>
          <td><%= section_configuration.color_desc %></td>
          <td><%= section_configuration.configuration_code %></td>
          <td><%= section_configuration.active %></td>
          <td><%= section_configuration.tariff_code %></td>
          <td><%= section_configuration.schedule_code %></td>
          <td><%= section_configuration.configuration_type_code %></td>
          <td><%= section_configuration.description %></td>
          <td>
            <%= link_to "Details", section_configuration_path(section_configuration), :class => 'btn btn-default btn-xs' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= render :partial => "sidebar" %>

app/views/section_configurations/new.html.erb
<%- model_class = SectionConfiguration -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/section_configurations/show.html.erb
<div class="col-lg-12">
  <ol class="breadcrumb">
    <li><%= link_to '<i class="fa fa-cogs"></i> Section Configurations'.html_safe, section_configurations_path %></li>
    <li class="active">Configuration <%= @section_configuration.id %></li>
  </ol>
</div>
<div class="col-lg-12">
  <%- model_class = SectionConfiguration -%>
  <table class="table table-bordered small">
    <tr>
      <th>
        <%= model_class.human_attribute_name(:tariff_id) %>
      </th>
      <td>
        <%= @section_configuration.tariff_id %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:schedule_id) %>
      </th>
      <td>
        <%= @section_configuration.schedule_id %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:configuration_type_id) %>
      </th>
      <td>
        <%= @section_configuration.configuration_type_id %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:color_desc) %>
      </th>
      <td>
        <%= @section_configuration.color_desc %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:color_desc_pda) %>
      </th>
      <td>
        <%= @section_configuration.color_desc_pda %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:configuration_code) %>
      </th>
      <td>
        <%= @section_configuration.configuration_code %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:active) %>
      </th>
      <td>
        <%= @section_configuration.active %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:tariff_code) %>
      </th>
      <td>
        <%= @section_configuration.tariff_code %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:schedule_code) %>
      </th>
      <td>
        <%= @section_configuration.schedule_code %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:configuration_type_code) %>
      </th>
      <td>
        <%= @section_configuration.configuration_type_code %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:description) %>
      </th>
      <td>
        <%= @section_configuration.description %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:tarrif_description_short) %>
      </th>
      <td>
        <%= @section_configuration.tarrif_description_short %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:schedule_description_short) %>
      </th>
      <td>
        <%= @section_configuration.schedule_description_short %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:include_holidays) %>
      </th>
      <td>
        <%= @section_configuration.include_holidays %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:only_parking) %>
      </th>
      <td>
        <%= @section_configuration.only_parking %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:fraction_type) %>
      </th>
      <td>
        <%= @section_configuration.fraction_type %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:fraction_price) %>
      </th>
      <td>
        <%= @section_configuration.fraction_price %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:max_time) %>
      </th>
      <td>
        <%= @section_configuration.max_time %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:price_per_hour) %>
      </th>
      <td>
        <%= @section_configuration.price_per_hour %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:price_per_minute) %>
      </th>
      <td>
        <%= @section_configuration.price_per_minute %>
      </td>
    </tr>
    <tr>
      <th>
        <%= model_class.human_attribute_name(:price_per_second) %>
      </th>
      <td>
        <%= @section_configuration.price_per_second %>
      </td>
    </tr>
  </table>
</div>