config/routes.rb
Rails.application.routes.draw do

  resources :deliverers do
    member do
      post 'refresh_map_view'
    end
  end
  devise_for :users
  root 'check_ins#index'

  resources :check_ins do
    collection do
      get 'import_csv'
      post 'process_csv'
      get 'delete_all'
      post 'confirm_delete_all'
      get 'show_on_map'
      post 'refresh_map_view'
    end
  end
  resources :sections do
    collection do
      get 'import_csv'
      post 'process_csv'
      get 'delete_all'
      post 'confirm_delete_all'
    end
    member do
      get 'show_per_time_slot'
      post 'refresh_per_time_slot'
      get 'show_per_day_of_week'
      post 'refresh_per_day_of_week'
      get 'show_avg_per_time_slot'
      post 'refresh_avg_per_time_slot'
      get 'show_avg_per_day_of_week'
      post 'refresh_avg_per_day_of_week'
      get 'show_check_ins_time_series'
      post 'refresh_check_ins_time_series'
      get 'download_csv_reports'
    end
  end
  resources :section_configurations do
    collection do
      get 'import_csv'
      post 'process_csv'
      get 'delete_all'
      post 'confirm_delete_all'
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "AreaDum Dataset" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <script src="https://maps.google.com/maps/api/js?v=3.2&sensor=false"></script>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><b>AreaDUM</b>Dataset</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= 'active' if controller_name == 'check_ins' %>"><%= link_to '<i class="fa fa-map-marker"></i>  Check-Ins'.html_safe, check_ins_path %></li>
            <li class="<%= 'active' if controller_name == 'sections' %>"><%= link_to '<i class="fa fa-road"></i> Sections'.html_safe, sections_path %></li>
            <li class="<%= 'active' if controller_name == 'section_configurations' %>"><%= link_to '<i class="fa fa-cogs"></i> Section Configurations'.html_safe, section_configurations_path %></li>
            <li class="<%= 'active' if controller_name == 'deliverers' %>"><%= link_to '<i class="fa fa-truck"></i> Deliverers'.html_safe, deliverers_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-user"></i>
                <%= "#{current_user.email}" %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to "<i class=\"fa fa-sign-out\"></i> Sign out".html_safe, destroy_user_session_path, :method => :delete %>
                </li>
              </ul>
            </li>          
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
          <%= bootstrap_flash %>
          <%= yield %>
      </div><!--/row-->

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AreaDum Dataset</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body class="devise-body">
  
    <div id="wrap">
      <div class="container">
        <div class="row">
          <div class="col-lg-3"></div>
          <div class="col-lg-6">
            <%= bootstrap_flash unless notice.blank? && alert.blank? %>
            <div class="text-center" style="margin-top: 50px; margin-bottom: 30px;">
              <h1 class="text-primary"><i class="fa fa-truck"></i> <b>AreaDUM</b></h1>
              <h4 class="text-muted">Dataset manager</h4>
            </div>
            <div class="col-lg-12">
              <%= yield %>
            </div>
          </div>
          <div class="col-lg-3"></div>
        </div>
      </div>
    </div>

    <div id="footer">
      <div class="container">
        <p class="version small pull-right footer-label">© <%= Date.today.year.to_s %> | <a class="version" href="https://www.dama.upc.edu/en" target="_blank">DAMA UPC</a> | <b>AreaDUM</b>Dataset</p>
      </div>
    </div>

  </body>
</html>